#!/bin/bash
# Generate release hal2vg binary
# Must have a static buildable hdf5 (ie not the one from apt)
# Must be run after tree is tagged and pushed to master.
# Use --keep to keep working directory for debugging.

mydir=$(dirname $(which $0))
source ${mydir}/releaseLib.sh

keep=no
if [ $1 = '--keep' ] ; then
    keep=yes
fi
set -beEu -o pipefail

buildDir=$(realpath -m build)
binBuildDir="${buildDir}/bin-tmp"

set -x
rm -rf ${binBuildDir}
mkdir -p ${binBuildDir}
cd ${binBuildDir}
git clone https://github.com/ComparativeGenomicsToolkit/hal2vg.git
cd hal2vg
git fetch --tags origin

REL_TAG=$(getLatestReleaseTag)
git checkout "${REL_TAG}"
git submodule update --init --recursive

# todo: update / figure out / remove hack:
cp ./build-tools/CMakeLists.txt ./deps/libbdsg-easy/deps/libhandlegraph/CMakeLists.txt

if [ $(man gcc | grep nehalem | wc -l) -ge 1 ]
then
	 # attempt to increase portability by using older architecture
	 # this make/sed/make thing is a hack to get around a linking error that just cropped up
	 CFLAGS="-march=nehalem" CXXFLAGS="-march=nehalem" make static -j 8 || true
	 sed -i deps/libbdsg-easy/deps/libbdsg/Makefile -e "s/-lomp//g"	 
	 CFLAGS="-march=nehalem" CXXFLAGS="-march=nehalem" make check-static
else
	 make static || true
	 sed -i deps/libbdsg-easy/deps/libbdsg/Makefile -e "s/-lomp//g"
	 make check-static
fi

cp hal2vg clip-vg halRemoveDupes halMergeChroms halUnclip filter-paf-deletions count-vg-hap-cov ${buildDir}/

